[feat]: Поправил пайплайны

diff --git a/.github/workflows/pipelines.yml b/.github/workflows/pipelines.yml
--- a/.github/workflows/pipelines.yml
+++ b/.github/workflows/pipelines.yml
@@ -41,12 +41,41 @@ jobs:
           git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
           ./mvnw clean package
   user-service-dockerize:
-    if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
     needs: user-service-test
     steps:
-      - name: 👉🏼 Устанавливаем sshpass
-        run: sudo apt update && sudo apt install -y sshpass
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
+
+      - name: 👉🏼 Инициализируем гит сабмодули
+        run: |
+          git clone https://github.com/heavenboards/user-service.git
+          cd ./user-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: |
+          cd ./user-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          chmod +x ./mvnw
+
+      - name: 👉🏼 Запускаем install + docker build + docker push
+        run: |
+          cd ./user-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          ./mvnw -DskipTests -DregistryUsername=${{ vars.CI_REGISTRY_USER }} -DregistryPassword='${{ vars.CI_REGISTRY_PASSWORD }}' clean install
   user-service-deploy:
     if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
@@ -89,12 +118,41 @@ jobs:
           git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
           ./mvnw clean package
   project-service-dockerize:
-    if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
     needs: project-service-test
     steps:
-      - name: 👉🏼 Устанавливаем sshpass
-        run: sudo apt update && sudo apt install -y sshpass
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
+
+      - name: 👉🏼 Инициализируем гит сабмодули
+        run: |
+          git clone https://github.com/heavenboards/project-service.git
+          cd ./project-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: |
+          cd ./project-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          chmod +x ./mvnw
+
+      - name: 👉🏼 Запускаем install + docker build + docker push
+        run: |
+          cd ./project-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          ./mvnw -DskipTests -DregistryUsername=${{ vars.CI_REGISTRY_USER }} -DregistryPassword='${{ vars.CI_REGISTRY_PASSWORD }}' clean install
   project-service-deploy:
     if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
@@ -137,12 +195,41 @@ jobs:
           git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
           ./mvnw clean package
   composer-service-dockerize:
-    if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
     needs: composer-service-test
     steps:
-      - name: 👉🏼 Устанавливаем sshpass
-        run: sudo apt update && sudo apt install -y sshpass
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
+
+      - name: 👉🏼 Инициализируем гит сабмодули
+        run: |
+          git clone https://github.com/heavenboards/composer-service.git
+          cd ./composer-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: |
+          cd ./composer-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          chmod +x ./mvnw
+
+      - name: 👉🏼 Запускаем install + docker build + docker push
+        run: |
+          cd ./composer-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          ./mvnw -DskipTests -DregistryUsername=${{ vars.CI_REGISTRY_USER }} -DregistryPassword='${{ vars.CI_REGISTRY_PASSWORD }}' clean install
   composer-service-deploy:
     if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
@@ -185,12 +272,41 @@ jobs:
           git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
           ./mvnw clean package
   board-service-dockerize:
-    if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
     needs: board-service-test
     steps:
-      - name: 👉🏼 Устанавливаем sshpass
-        run: sudo apt update && sudo apt install -y sshpass
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
+
+      - name: 👉🏼 Инициализируем гит сабмодули
+        run: |
+          git clone https://github.com/heavenboards/board-service.git
+          cd ./board-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: |
+          cd ./board-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          chmod +x ./mvnw
+
+      - name: 👉🏼 Запускаем install + docker build + docker push
+        run: |
+          cd ./board-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          ./mvnw -DskipTests -DregistryUsername=${{ vars.CI_REGISTRY_USER }} -DregistryPassword='${{ vars.CI_REGISTRY_PASSWORD }}' clean install
   board-service-deploy:
     if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
@@ -233,12 +349,41 @@ jobs:
           git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
           ./mvnw clean package
   task-service-dockerize:
-    if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
     needs: task-service-test
     steps:
-      - name: 👉🏼 Устанавливаем sshpass
-        run: sudo apt update && sudo apt install -y sshpass
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
+
+      - name: 👉🏼 Инициализируем гит сабмодули
+        run: |
+          git clone https://github.com/heavenboards/task-service.git
+          cd ./task-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: |
+          cd ./task-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          chmod +x ./mvnw
+
+      - name: 👉🏼 Запускаем install + docker build + docker push
+        run: |
+          cd ./task-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+          ./mvnw -DskipTests -DregistryUsername=${{ vars.CI_REGISTRY_USER }} -DregistryPassword='${{ vars.CI_REGISTRY_PASSWORD }}' clean install
   task-service-deploy:
     if: ${{ github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
